services:
  minecraft:
    image: itzg/minecraft-server
    environment:
      EULA: "TRUE"
      TYPE: "PAPER"
      MEMORY: "2G"
    ports:
      - "12000:25565"
    volumes:
      - minecraft-data:/data
      - ./plugins:/data/plugins
    networks:
      - internal
    restart: unless-stopped

  landing:
    build: ./landing
    ports:
      - "80:3000"
    networks:
      - public
    restart: unless-stopped

  prometheus:
    image: prom/prometheus
    ports:
      - "8083:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    networks:
      - internal
    restart: unless-stopped

  node-exporter:
    image: prom/node-exporter
    networks:
      - internal
    restart: unless-stopped

  cadvisor:
    image: gcr.io/cadvisor/cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - internal
    restart: unless-stopped

  grafana:
    image: grafana/grafana
    ports:
      - "8081:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    networks:
      - internal
      - public
    restart: unless-stopped

volumes:
  minecraft-data:
  prometheus-data:
  grafana-data:

networks:
  internal:
  public:
