services:
  minecraft:
    image: itzg/minecraft-server
    environment:
      EULA: "TRUE"
      TYPE: "PAPER"
      MEMORY: "2G"
    ports:
      - "12000:25565"
    volumes:
      - minecraft-data:/data
      - ./plugins:/data/plugins
    networks:
      - internal
    restart: unless-stopped

  landing:
    build: ./landing
    ports:
      - "80:3000"
    networks:
      - public
    restart: unless-stopped

volumes:
  minecraft-data:

networks:
  internal:
  public:
